blog/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# Project: myblog 
# Software: PyCharm
# Time    : 2018-09-24 11:37
# File    : urls.py
# Author  : 天晴天朗
# Email   : tqtl@tqtl.org
from django.conf.urls import url
from django.contrib import admin
from . import views

# from blog import views
# import blog.views as bv

urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_pages, name='edit_page'),
    url(r'^edit/action$', views.edit_action, name='edit_action'),
]

content/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# Project: myblog 
# Software: PyCharm
# Time    : 2018-09-24 11:37
# File    : urls.py
# Author  : 天晴天朗
# Email   : tqtl@tqtl.org
from django.conf.urls import url
from django.contrib import admin
from . import views

# from blog import views
# import blog.views as bv

urlpatterns = [
    url(r'^index/$', views.content),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# from blog import views
# import blog.views as bv

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^content/', include('content.urls')),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)

    def __unicode__(self):  # Python2的用法；
        # def __str__(self):   Python3的用法；
        return self.title

content/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from blog import models


# Create your views here.

def index(request):
    # return HttpResponse('Hello World!cuixiaozhao')
    # return render(request, 'blog/index.html', {'hello': 'Hello,Django Blog!'})
    # article = models.Article.objects.get(pk=3)
    articles = models.Article.objects.all()
    # print(articles)
    return render(request, 'blog/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


def edit_pages(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id', '0 ')
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request,'blog/article_page.html',{'article':article})

content/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def content(request):
    return render(request, 'content/content.html', {'content': 'Hello Content! cuixiaozhao'})

templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ArticlePages</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<h1>{{ article.title  }}</h1>
<br></br>
<h3>{{ article.content }}</h3>
<br>
<br>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>EditPages</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    {% if article %}
        <input type="hidden" name="article_id" value="{{ article.id }}">
        <label for="">文章标题
            <input type="text" name="title" value="{{ article.title }}">
        </label>
        <br>
        <label for="">文章内容
            <input type="text" name="content" value="{{ article.content }}">
        </label>
        <br>
    {% else %}
        <input type="hidden" name="article_id" value="0">
        <label for="">文章标题
            <input type="text" name="title">
        </label>
        <br>
        <label for="">文章内容 
            <input type="text" name="content">
        </label>
        <br>
    {% endif %}
    <input type="submit" value="提交">
</form>
</body>
</html>

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DjangoTemplates</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">新文章</a>
</h1>
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %} ">{{ article.title }}</a>
    <br>
{% endfor %}

</body>
</html>

templates/content/content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DjangoTemplates</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
{#<h1>Hello,Blog!</h1>#}
<h1>{{ content }}</h1>
</body>
</html>